name: Build and release capmvm images (CloudHypervisor) - Manual

on:
  workflow_dispatch:
    branches: [main]

defaults:
  run:
    working-directory: capmvm/cloudhypervisor

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make
          make push