name: Build and release kernel images (Cloud Hypervisor)

on:
  pull_request:
    paths:
      - 'experimental/cloudhypervisor/kernel/**'
    branches: [main]
  push:
    paths:
      - 'experimental/cloudhypervisor/kernel/**'
    branches: [main]

defaults:
  run:
    working-directory: experimental/cloudhypervisor/kernel

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 5.12 ]
    steps:
      - uses: actions/checkout@v2
      - name: Build kernel
        run: make
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ 5.12 ]
    env:
      KERNEL_VERSIONS: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make
          make push