name: Build and release base ubuntu images

on:
  pull_request:
    paths:
      - 'flintlock/base-ubuntu/**'
    branches: [main]
  push:
    paths:
      - 'flintlock/base-ubuntu/**'
    branches: [main]

defaults:
  run:
    working-directory: flintlock/base-ubuntu

jobs:
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: make
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make IS_LATEST=true
          make push IS_LATEST=true